import type { Role } from '../model/role';

/**
 * The adapter boundary. An adapter owns only a CLI's launch arguments per role,
 * its readiness probe, and its continue flag — nothing else. Terminal creation,
 * brief handling, result handling, watching, validation, journaling and reset
 * are all shared and live outside the adapter (Requirement 14.1).
 *
 * The first pass ships a single adapter, {@link ClaudeAdapter}.
 */
export interface Adapter {
  /** Stable adapter identifier. */
  readonly id: 'claude';

  /**
   * Check that the underlying CLI is present and usable. Runs before every
   * stage because CLIs self-update (Requirement 14.2). When `ok` is false the
   * `reason` is a non-empty explanation the extension surfaces to the user
   * (Requirement 14.4).
   */
  probe(): Promise<ProbeResult>;

  /**
   * Build the launch arguments for one stage. Pure: it computes `shellPath`,
   * `shellArgs` and an optional `env` from the request and does not touch the
   * filesystem, terminal or journal.
   */
  launch(req: LaunchRequest): LaunchSpec;

  /**
   * Build the launch arguments to reopen an existing session with no prompt:
   * `claude --resume <id> <permission flags> <run-dir grant>` (Requirement
   * 3.3, 3.4). Used by the View command to show a sub-agent's conversation
   * after its terminal is gone.
   */
  attach(req: { role: Role; runId: string; sessionId: string }): LaunchSpec;
}

/** The result of an adapter probe (Requirements 14.3, 14.4). */
export interface ProbeResult {
  /** The reported CLI version string (empty when the probe could not read it). */
  version: string;
  /** Whether the CLI is present and usable. */
  ok: boolean;
  /** Non-empty explanation when `ok` is false; omitted when `ok` is true. */
  reason?: string;
}

/** Everything the adapter needs to construct a stage launch. */
export interface LaunchRequest {
  /** The role being launched; selects the permission row (Requirement 15). */
  role: Role;
  /** The model identifier passed as `--model`. */
  model: string;
  /** Optional reasoning effort passed as `--effort`. */
  effort?: string;
  /** The initial prompt handed to the CLI. */
  prompt: string;
  /**
   * The run id whose `.baiton/runs/<run-id>/` directory the role may write to
   * (Requirement 15.4).
   */
  runId: string;
  /**
   * True when a prior session should be resumed via `--resume`/`-c`. False
   * launches a fresh session (Requirements 13.2, 13.3).
   */
  resume: boolean;
  /**
   * The Claude `--session-id` UUID passed on a fresh launch, generated by the
   * Run_Queue and recorded in the journal start record (Requirement 3.1).
   */
  sessionId: string;
  /**
   * The prior Session_Id to resume with `--resume <id>` when set; when
   * `resume` is true and this is absent, the adapter falls back to `-c`
   * (Requirement 3.2).
   */
  resumeSessionId?: string;
}

/**
 * A ready-to-run terminal launch. The extension creates the terminal with this
 * `shellPath`/`shellArgs` and no intervening shell (Requirement 11.1).
 */
export interface LaunchSpec {
  /** The executable to run as the terminal's own process. */
  shellPath: string;
  /** The arguments passed to that executable. */
  shellArgs: string[];
  /** Optional environment overrides for the launched process. */
  env?: Record<string, string>;
}
